apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:6TO5J2RCgY8dJmacUWgpqva4ySLkVqzRbq4ouOakh+RSMp67,iv:wkHr5XQLzBQ+jsDjMt8RXA8RrwtM1/fuhB5iPuxsxeo=,tag:sioDhI94ojeaiiXF6ViO4w==,type:str]
    credentials.json: ENC[AES256_GCM,data:lX0GZxfv9ShCix9ayOgou5ollB0HqHH42aD+YOH8LCCz6ivm8zOMcNA7y3imc80T55Rq4FDs84j/P6Y8viQCJCvQGt2S6M7/SlFvcqo0nwXH2cyKk7nvCiaqOmv3UYo5V5uswvjBWbZRWb4+tKZFY8Ac7cs6+YDVhfwmRtwBDrU4M7XugTB64BJF+ICPywZDd+BAqyGSz+WqLSxAbvn6RP6aq8YwS4dLBZ95vIlGsQ==,iv:LGEaIJYrg/UQ8J9x/uFwMT11Iaf+/RAQD9jrS6Vr4lw=,tag:3yikOfV1rzHOBrpVAgz5Tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rsl8yacgcreq5g0m0t084ucezwnuxvue4edkp7rrdj3vrzmqupgqpz87kg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyckdBYi8vajgwSmtBcnZB
            MnRvclFkU2p5WVZnSDFPL21vcTBubVZGRXdVClEzcS9Rek8zbXdRRWxFUExIOXZH
            M2tsN0srQ202U1piZzlxT3poWnlvOUkKLS0tIGpMcGtnSTJxY0N3ZE9CQWJwb0Zt
            RmhjU1VYTWViam4rMVV0RUhLNklONEEKEhgEa70pd4rXRyW4/oL0HsabbjdnU2xw
            sBFBfMQaxDHkfUQMyQ++JtIltL+WrlCIUOLrpix9jv08pO+7tl6F0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-17T17:17:40Z"
    mac: ENC[AES256_GCM,data:tMihLWv9sShWbrNuAYzfmXp2q6No4X7R0fb3DLi25MZMfkIlXPmhQcmoG0IEAU7zyp6T08+/xjsAOj/Bl1APKVzKQyKkSmZVwbYciMTcP8RKeREZXmWKkOXxqaEX3SRfol3kkhCTnp7QNTVOn7CeGP2TPuf8GnydTdDv8JxPOkA=,iv:xnc3VXj0uUUNQmt5rg7CgRVbG3qQh3RVm5OjNy0PL0Y=,tag:ThduTeP/SIsMpM6U035FnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
